version: "3.8"
services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=ithreex
      - POSTGRES_PASSWORD=ithreex123
      - POSTGRES_DB=ithreex
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./backend/database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ithreex"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
